development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://nkbkbemphgfdus:anj8hRoBGrfBCscm0Cfd-u6eim@ec2-54-243-203-179.compute-1.amazonaws.com:5432/d2a39bsekgstrv
